### ISSUE TITLE
[Sounds] Image buttons are not displayed on Safari

### ISSUE THREAD

**Issue by thaisguigon** [cbellino/hubside-quotes#1]
When I access the Sounds tab on Safari, this is what I see:

<img width="1810" alt="Capture d’écran 2019-04-19 à 15 06 25" src="https://user-images.githubusercontent.com/3098428/56425463-bca3d680-62b4-11e9-8311-769d97c346b0.png">

Clicking on a square does not trigger a sound either.

**Comment by cbellino** [comment]
I disabled the SW cache for now as i suspect this issue might be coming from here. Can you clear your cache/sw and confirm if the fix worked on your side?

**Comment by thaisguigon** [comment]
Thanks, @cbellino :D

Sooo, now image buttons are displayed but never all of them, there is always at least one that does not load. And when I click on the loaded ones, the sound is played but then the screen goes blank.

The console displays the following error when the screen goes blank:

```
[Error] TypeError: undefined is not an object (evaluating 'U.pause')
  (anonymous function) — SoundItem.tsx:25
  ha — react-dom.production.min.js:4439
  (anonymous function) — react-dom.production.min.js:5048
  [native code]
  Ba — react-dom.production.min.js:5067
  ui — react-dom.production.min.js:3473
  ui
  (anonymous function) — SoundItem.tsx:53
```

So it seems to me that `audio.pause()` is being called when audio is still `undefined`.

I'm opening a PR to attempt a fix for the `undefined` audio issue, however I don't know about the fact that some image buttons are not displayed.

**Comment by thaisguigon** [comment]
I'm closing this issue as it was mostly solved by deactivating the Service Worker (for Safari Desktop). Another specific might be opened about iOS.
